name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip libncurses6 libncurses-dev openjdk-11-jdk \
            wget git python3-pip

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install --upgrade buildozer

      - name: Set up Android SDK (cmdline tools)
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest
        shell: bash

      - name: Accept SDK licenses
        run: |
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        env:
          ANDROID_HOME: $HOME/android-sdk
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
        shell: bash

      - name: Install Android build tools
        run: |
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" "platforms;android-31" "build-tools;31.0.0"
        env:
          ANDROID_HOME: $HOME/android-sdk
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
        shell: bash

      - name: Build APK with Buildozer
        run: |
          buildozer android debug
        env:
          ANDROIDSDK: $HOME/android-sdk
          ANDROID_HOME: $HOME/android-sdk
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
