name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip openjdk-11-jdk python3-pip python3-setuptools python3-virtualenv libffi-dev libssl-dev libjpeg-dev zlib1g-dev

      - name: Install Buildozer and dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install cython==0.29.33
          pip install buildozer==1.5.0

      - name: Set up Android SDK (cmdline tools)
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools.zip
          mv cmdline-tools latest
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Accept SDK licenses and install SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager --update
          sdkmanager "build-tools;31.0.0" "platform-tools" "platforms;android-31" "ndk;21.4.7075529"

      - name: Build APK with Buildozer
        run: |
          buildozer android debug
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
          ANDROIDSDK: ${{ env.ANDROID_HOME }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Pillsperfections-APK
          path: bin/*.apk
