name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system packages
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-11-jdk libncurses5

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Set up Android SDK
        run: |
          mkdir -p ~/.android
          echo "### Accept SDK licenses" > ~/.android/repositories.cfg
          yes | sdkmanager --licenses || true

      - name: Accept SDK licenses (manual fallback)
        run: |
          yes | sdkmanager --licenses || true

      - name: Install Android build tools
        run: |
          sdkmanager "build-tools;31.0.0" "platform-tools" "platforms;android-31"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Pillsperfections-APK
          path: bin/*.apk
