name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-11-jdk libffi-dev libssl-dev libncurses5

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept SDK licenses
      run: yes | sdkmanager --licenses

    - name: Install Android build tools
      run: sdkmanager "build-tools;31.0.0" "platform-tools" "platforms;android-31"

    - name: Build APK
      run: buildozer android debug
